name: Wiz Security Scan

on:
  workflow_run:
    workflows: ["Build and Push Container Image"]
    types:
      - completed

jobs:
  wiz-docker-scan:
    # Only run on the published version-tagged image
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v')
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - name: Download & Authenticate Wiz CLI
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
        run: |
          curl -Lo wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64
          chmod +x wizcli
          ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and Scan Published Image
        env:
            IMAGE_REPOSITORY: ghcr.io/${{ github.repository_owner }}/${{ vars.APP_NAME }}
            IMAGE_SHA: ${{ github.event.workflow_run.head_sha }}
            WIZ_PROJECT: ${{ vars.WIZ_PROJECT }}
        run: |
          IMAGE_URL="$IMAGE_REPOSITORY:sha-${IMAGE_SHA:0:7}"
          echo "Receiving published image version: ${{ github.event.workflow_run.head_branch }}"
          echo "Pulling and scanning image: $IMAGE_URL"
          docker pull "$IMAGE_URL"
          ./wizcli scan container-image "$IMAGE_URL" --projects="$WIZ_PROJECT"